"""Default categories seeded for new users."""

from __future__ import annotations

from whatsapp_platform.domain.entities.finance import CategoryType

DEFAULT_EXPENSE_CATEGORIES: list[dict] = [
    {"name": "Makanan & Minuman", "icon": "🍜", "type": CategoryType.EXPENSE},
    {"name": "Transport", "icon": "🚗", "type": CategoryType.EXPENSE},
    {"name": "Belanja", "icon": "🛒", "type": CategoryType.EXPENSE},
    {"name": "Tagihan & Utilitas", "icon": "💡", "type": CategoryType.EXPENSE},
    {"name": "Kesehatan", "icon": "🏥", "type": CategoryType.EXPENSE},
    {"name": "Hiburan", "icon": "🎮", "type": CategoryType.EXPENSE},
    {"name": "Pendidikan", "icon": "📚", "type": CategoryType.EXPENSE},
    {"name": "Pakaian", "icon": "👕", "type": CategoryType.EXPENSE},
    {"name": "Investasi", "icon": "📈", "type": CategoryType.EXPENSE},
    {"name": "Sosial", "icon": "🤝", "type": CategoryType.EXPENSE},
    {"name": "Lainnya", "icon": "💸", "type": CategoryType.EXPENSE},
]

DEFAULT_INCOME_CATEGORIES: list[dict] = [
    {"name": "Gaji", "icon": "💰", "type": CategoryType.INCOME},
    {"name": "Freelance", "icon": "💼", "type": CategoryType.INCOME},
    {"name": "Bonus", "icon": "🎁", "type": CategoryType.INCOME},
    {"name": "Bisnis", "icon": "🏢", "type": CategoryType.INCOME},
    {"name": "Investasi", "icon": "📊", "type": CategoryType.INCOME},
    {"name": "Hadiah", "icon": "🎀", "type": CategoryType.INCOME},
    {"name": "Lainnya", "icon": "💵", "type": CategoryType.INCOME},
]

ALL_DEFAULT_CATEGORIES = DEFAULT_EXPENSE_CATEGORIES + DEFAULT_INCOME_CATEGORIES

EXPENSE_KEYWORD_MAP: dict[str, str] = {
    "makan": "Makanan & Minuman",
    "minum": "Makanan & Minuman",
    "kopi": "Makanan & Minuman",
    "resto": "Makanan & Minuman",
    "restoran": "Makanan & Minuman",
    "cafe": "Makanan & Minuman",
    "warteg": "Makanan & Minuman",
    "bakso": "Makanan & Minuman",
    "nasi": "Makanan & Minuman",
    "bensin": "Transport",
    "bbm": "Transport",
    "ojek": "Transport",
    "grab": "Transport",
    "gojek": "Transport",
    "taksi": "Transport",
    "bus": "Transport",
    "kereta": "Transport",
    "toll": "Transport",
    "parkir": "Transport",
    "listrik": "Tagihan & Utilitas",
    "air": "Tagihan & Utilitas",
    "internet": "Tagihan & Utilitas",
    "wifi": "Tagihan & Utilitas",
    "pulsa": "Tagihan & Utilitas",
    "token": "Tagihan & Utilitas",
    "belanja": "Belanja",
    "supermarket": "Belanja",
    "indomaret": "Belanja",
    "alfamart": "Belanja",
    "shopee": "Belanja",
    "tokopedia": "Belanja",
    "obat": "Kesehatan",
    "dokter": "Kesehatan",
    "rs": "Kesehatan",
    "klinik": "Kesehatan",
    "game": "Hiburan",
    "nonton": "Hiburan",
    "bioskop": "Hiburan",
    "netflix": "Hiburan",
    "spotify": "Hiburan",
    "buku": "Pendidikan",
    "kursus": "Pendidikan",
    "sekolah": "Pendidikan",
    "kuliah": "Pendidikan",
    "baju": "Pakaian",
    "sepatu": "Pakaian",
    "celana": "Pakaian",
    "investasi": "Investasi",
    "saham": "Investasi",
    "reksa": "Investasi",
    "sumbangan": "Sosial",
    "donasi": "Sosial",
    "hadiah": "Sosial",
}

INCOME_KEYWORD_MAP: dict[str, str] = {
    "gaji": "Gaji",
    "salary": "Gaji",
    "upah": "Gaji",
    "freelance": "Freelance",
    "proyek": "Freelance",
    "project": "Freelance",
    "bonus": "Bonus",
    "thr": "Bonus",
    "bisnis": "Bisnis",
    "usaha": "Bisnis",
    "jualan": "Bisnis",
    "dividen": "Investasi",
    "bunga": "Investasi",
    "hadiah": "Hadiah",
    "kado": "Hadiah",
}
