"""SessionStatus Enum value object."""

from enum import Enum


class SessionStatus(str, Enum):
    INITIALIZING = "INITIALIZING"
    AWAITING_QR = "AWAITING_QR"
    AWAITING_PAIRING_CODE = "AWAITING_PAIRING_CODE"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    DISCONNECTING = "DISCONNECTING"
    DISCONNECTED = "DISCONNECTED"
    RECONNECTING = "RECONNECTING"
    FAILED = "FAILED"
    LOGGED_OUT = "LOGGED_OUT"
